### ISSUE TITLE
When pkg-config is missing, build fails in a strange way

### ISSUE THREAD

**Issue by mojca** [msharov/snownews#35] opened 2019-02-25 07:12 UTC
The code should probably check whether `pkg-config` exists before calling it:
```
Running configure ...
./configure: line 209: --exists: command not found
```

**Comment by maxice8** [comment] 2020-06-13 19:35
This most likely is the cause of #41 (besides the original poster not having libxml2-devel installed)

**Comment by msharov** [comment] 2021-04-08 14:56
Fixed by commit 268ef84660c03df29e8f155c3570092add1596cd

**Closed by msharov** 2021-04-08 14:56 UTC
Labels: bug
