### ISSUE TITLE
Void Linux Support / libxml-2.0

### ISSUE THREAD

**Issue by ralphee** [msharov/snownews#41] opened 2020-01-29 10:47 UTC
would be great to be able to compile on void linux. Currently `./configure` will warn of missing libxml2 albeit its [installed](http://ix.io/28CR)

**Comment by Fireobirdy** [comment] 2020-02-03 21:56
Same problem here.
`libxml2-dev ist schon die neueste Version (2.9.4+dfsg1-2.2+deb9u2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
june@ddd:~/snownews-1.6.10$ ./configure
./configure: 209: ./configure: --exists: not found
required library libxml-2.0 is missing
june@ddd:~/snownews-1.6.10$
`

**Comment by maxice8** [comment] 2020-06-13 19:34
the --exists switch only appears to be used in the context of getting where pkgconfig is from ?

is pkg-config package installed in your system ?

**Comment by maxice8** [comment] 2020-06-13 19:34
@ralphee your own ix.io shows that

[-] libxml2-devel-2.9.10_1              Library providing XML and HTML support - development files

is not installed

**Comment by msharov** [comment] 2021-04-08 14:57
Fixed by commit 268ef84660c03df29e8f155c3570092add1596cd

**Comment by msharov** [comment] 2021-04-08 14:58
Also, duplicate of #35

**Closed by msharov** 2021-04-08 14:57 UTC
