### ISSUE TITLE
Compilation fails under musl

### ISSUE THREAD

**Issue by maxice8** [msharov/snownews#42] opened 2020-06-13 19:37 UTC
musl requires limits.h for PATH_MAX, but because config.h has `#pragma once`, it is not included in all files that use PATH_MAX and expect PATH_MAX to be provided by `limits.h` included in `config.h`

**Comment by msharov** [comment] 2021-04-08 15:03
#pragma once only prevents including config.h multiple times. The first time it is always included, and limits.h with it. If you are still having this problem, please post the error messages you get during the build and the compiler version.

**Comment by msharov** [comment] 2021-04-08 19:43
This appears to be a duplicate of #34

**Closed by msharov** 2021-04-08 19:43 UTC
Labels: bug, duplicate
